version: '3.9'
# docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  meilisearch:
    ports:
      - "7700:7700"
    environment:
      MEILI_ENV: development

  backend:
    build:
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend/src:/app/src:ro
    environment:
      NODE_ENV: development

  worker:
    volumes:
      - ./worker/app:/app/app:ro
    environment:
      LOG_LEVEL: DEBUG

  web:
    build:
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./web/src:/app/src:ro

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"
